version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/portal"
    target-branch: "develop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/harvester"
    target-branch: "develop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/service"
    target-branch: "develop"
    schedule:
      interval: "weekly"
