stages:
  - build

pages:
  stage: build
  script:
    - mkdir public
    - docker run --user $(id -u):$(id -g) --rm -v $PWD:/docs humangeo/aglio -i api.apib -o public/index.html
  artifacts:
    paths:
    - public
  tags:
  - dev
  - factory
  only:
    - develop
