version: '3.1'
services:
  postgres:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=surf
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=surf
    healthcheck:
        test: su postgres -c "psql -c "SELECT 'DBD::Pg ping test'""
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile-local
    environment:
      - DJANGO_SETTINGS_MODULE=surf.settings.local
      - DO_DJANGO_INIT=true
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - .:/src
    links:
      - postgres:database
    depends_on:
      - postgres
    restart: unless-stopped
