version: '3.1'
services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=surf
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=surf
    healthcheck:
        test: psql -U surf surf -c "SELECT 'DBD::Pg ping test'"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uwsgi --honour-stdin --http 0.0.0.0:8080 --wsgi-file surf/wsgi.py --py-autoreload=3 --processes 2
    environment:
      - DJANGO_SETTINGS_MODULE=surf.settings.local
      - DJANGO_FRONTEND_DOMAIN=localhost:3000
      - DJANGO_PROTOCOL=http
      - DJANGO_DEBUG=1
      - PYTHONIOENCODING=UTF-8
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/src
    links:
      - postgres:database
    depends_on:
      - postgres

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8081:8080"

volumes:
  postgres_database:
