version: '3.1'


services:

  postgres:
    image: postgres:12
    volumes:
      - postgres_database:/var/lib/postgresql/data
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=edushare
    healthcheck:
        test: psql -U postgres edushare -c "SELECT 'DBD::Pg ping test'"
    labels:
      nl.surfcatalog.db: "postgres"
    ports:
      - "127.0.0.1:5432:5432"

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8081:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
      - ./elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic/repositories:/usr/share/elasticsearch/repositories
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 127.0.0.1:9200:9200

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

volumes:
  postgres_database:
  elastic-data:
