version: '3.1'
services:
  postgres:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=surf
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=surf
    healthcheck:
        test: psql -U surf surf -c "SELECT 'DBD::Pg ping test'"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uwsgi --honour-stdin --http 0.0.0.0:8080 --wsgi-file surf/wsgi.py --py-autoreload=3 --processes 4 --static-map /static=/src/static
    environment:
      - DJANGO_SETTINGS_MODULE=surf.settings.local
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - .:/src
    links:
      - postgres:database
    depends_on:
      - postgres
    restart: unless-stopped

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "8081:8080"
