version: '3.1'


services:

  service:
    build:
      context: service
      dockerfile: Dockerfile
    command: uwsgi --ini uwsgi.ini --py-autoreload=3
    environment:
      - PYTHONIOENCODING=UTF-8
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=surf.settings.service
      - DJANGO_POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - DJANGO_POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - DJANGO_BACKEND_DOMAIN=${DJANGO_BACKEND_DOMAIN}
      - DJANGO_FRONTEND_DOMAIN=${DJANGO_FRONTEND_DOMAIN}
      - DJANGO_PROTOCOL=${DJANGO_PROTOCOL}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - EDUREP_SOAP_SUPPLIER_ID=${EDUREP_SOAP_SUPPLIER_ID}
      - EDUREP_XML_API_ENDPOINT=${EDUREP_XML_API_ENDPOINT}
      - EDUREP_SOAP_API_ENDPOINT=${EDUREP_SOAP_API_ENDPOINT}
      - EDUREP_JSON_API_ENDPOINT=${EDUREP_JSON_API_ENDPOINT}
      - VOOT_API_ENDPOINT=${VOOT_API_ENDPOINT}
      - ELASTIC_SEARCH_USERNAME=${ELASTIC_SEARCH_USERNAME}
      - ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
      - ELASTIC_SEARCH_URL=${ELASTIC_SEARCH_URL}
      - ELASTIC_SEARCH_HOST=${ELASTIC_SEARCH_HOST}
      - SEARCH_CLIENT=${SEARCH_CLIENT}
    ports:
      - "127.0.0.1:8000:8080"
    volumes:
      - ./service:/usr/src/app
    links:
      - postgres:database
    depends_on:
      - postgres
