version: '3.1'


services:

  service:
    build: .
    command: uwsgi --ini uwsgi.ini --py-autoreload=3
    environment:
      - PYTHONIOENCODING=UTF-8
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=surf.settings.service
      - APPLICATION_MODE=${APPLICATION_MODE}
      - POL_DJANGO_DEBUG=${POL_DJANGO_DEBUG}
      - POL_DJANGO_POSTGRES_USER=${POL_DJANGO_POSTGRES_USER}
      - POL_DJANGO_POSTGRES_PASSWORD=${POL_DJANGO_POSTGRES_PASSWORD}
      - POL_ELASTIC_SEARCH_PASSWORD=${POL_ELASTIC_SEARCH_PASSWORD}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "127.0.0.1:8000:8080"
    volumes:
      - ./service:/usr/src/app
    links:
      - postgres:database
    depends_on:
      - postgres
