version: '3.1'


services:

  service:
    build:
      dockerfile: "service/Dockerfile"
      context: .
    command: /usr/bin/supervisord
    stdin_open: true
    tty: true
    environment:
      - PYTHONIOENCODING=UTF-8
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=surf.settings.service
      - APPLICATION_MODE=${APPLICATION_MODE}
      - POL_DJANGO_DEBUG=${POL_DJANGO_DEBUG}
      - POL_DJANGO_POSTGRES_USER=${POL_DJANGO_POSTGRES_USER}
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./service:/usr/src/app
      - ./media:/usr/src/media
      - ./environments/localhost/invoke.yml:/usr/src/environments/localhost/invoke.yml
    links:
      - postgres:database
    depends_on:
      - postgres

  harvester:
    build:
      dockerfile: "harvester/Dockerfile"
      context: .
    stdin_open: true
    tty: true
    environment:
      - PYTHONIOENCODING=UTF-8
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=harvester.settings
      - APPLICATION_MODE=${APPLICATION_MODE}
      - POL_DJANGO_DEBUG=${POL_DJANGO_DEBUG}
      - POL_DJANGO_POSTGRES_USER=${POL_DJANGO_POSTGRES_USER}
    ports:
      - "127.0.0.1:8888:8080"
      - "127.0.0.1:5555:5555"
    volumes:
      - ./harvester:/usr/src/app
      - ./environments/localhost/invoke.yml:/usr/src/environments/localhost/invoke.yml
    links:
      - postgres:database
    depends_on:
      - postgres
