version: '3.1'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - /docker/surf-backend/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /volumes/surf/media:/src/media
    restart: unless-stopped
