version: '3.1'


services:
  postgres:
    image: postgres:11
    volumes:
      - postgres_database:/var/lib/postgresql/data
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=surf
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=surf
      - DJANGO_POSTGRES_PASSWORD=${POL_DJANGO_POSTGRES_PASSWORD}
    healthcheck:
        test: psql -U surf surf -c "SELECT 'DBD::Pg ping test'"
    labels:
      nl.surfcatalog.db: "postgres"
    ports:
      - "127.0.0.1:5432:5432"

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8081:8080"

volumes:
  postgres_database:
